## Simple questions, complex answers

Often we need to make decisions regarding complex systems with incomplete information. For example, we might need to decide 

When we need to make decisions about those systems, such as which schools to send our children to or which programs to fund, we often focus on the outputs and outcomes of those systems. When these decisiosn get made over and over again, the system will optimize for those outcomes. Often, if we do not examine the system carefully, this will create unintended outcomes that are opposite of what we were trying to achieve. We need to dig into systems to understand how they produce the outcomes we see, and get really clear about what we are trying to optimize for and why. 

## school ratings

My wife and I recently decided to move. We spent a lot of time looking at houses. We knew that we liked the neighborhood school where we currently lived, but we considered moving to other neighborhoods and wanted to know how 

Mother Jones recently published a piece on school ratings, families' housing decisions, and segregation. Rating systems have become common on real estate websites, and factor heavily into parents' decision about which neighborhoods are desireable. 

Because these ratings are based mostly on test scores, and test scores are highly correlated with the racial make-up of schools, they de facto exacerbate racial segreation in schools. Couple this with more direct forms of racism, it can be a really prenicious problem to solve. 

Cathy O'Neill shares a similar example around the college rankings in U.S. News. The rankings highly value things like how comptetitive acceptance (i.e. low acceptance rates), student-teacher ratios, and the precentage of students who gave to their alma mater after graudation. 

## Thinking in Systems

These systems are examples what Donnella Meadows calls reinforcing feedback loops. Reinforcing feedback loops, especially when they're not fully understood, have the tendency to spiral out of control. 

In these two examples, we only actually see a small part of the loops. The stuff we actually care about is the part of the loop that we don't actually see. I would imagine that, when asking what they care about in a child's education, it would be things like critical thinking, a strong sense of self, and the ability to reach their goals. 

But in fact, the things we've optimized for are only tenuously associated with those things. They are more closely associated with race, class, and privledge. We've created a system that rewards things that, in fact, many belive should be equalized through education. 

## rigorous evaluations

Results for America recently published a piece called "Moneyball for Workforce Development". The gist is that in the reauthorization of WIOA, the federal goverment should dedicate more money to rigorous evaluation. Rigorous evaluation in this case is synonymous with randomized control trials. 

Randomized control trials take the premise that randomization of individuals to a treatment or program factors out differences between treatment and control, either before assignment or after assignment but before measuring outcomes. Inhenrent is the idea that measuring outcomes will tell you all you need to know. 

The report does argue that more innovative outcome measures are needed, and it nowhere suggests that we should not evaluate implmentation alongside outcomes. However, I belive that relying so heavily on RCTs for evaluation can lead to optimizing for things that have unintendend, potentially negative consequences. 

For example, it seems likely that optimizing for job placement post program would lead to students being placed in low-wage jobs with little opportunity for advancement. Optimzing for education credentials may lead to biased program acceptance, leaving participants who struggle with basic literacy skills out of the opportunity altogether - if you randomize **after** program acceptance, you wouldn't know how that changes outcomes.

## Conclusion

We have to be really careful, when dealing with complex systems, how we are building the kinds of systems we want. Systems with reinforcing feedback loops can very easily create the the opposite outcomes we are looking for if we are not careful. 
