---
draft: true
---

```{r setup}

library(tidyverse)
library(rethinking)
library(jtcr)

theme_set(theme_jtc())

url <- "https://www.baseball-reference.com/data/war_archive-2019-10-03.zip" 

temp <- tempfile()
download.file(url, temp)

batting <- read_csv(unz(temp, "war_daily_bat.txt"), guess_max = 15000,
                    na = c("", "NA", "NULL")) %>%
    janitor::clean_names() 

pitching <- read_csv(unz(temp, "war_daily_pitch.txt"), guess_max = 20000,
                     na = c("", "NA", "NULL")) %>%
    janitor::clean_names() 

unlink(temp)

```


```{r allstar}

batting %>%
    filter(year_id == 2019, pitcher == "N") %>%
    ggplot(aes(salary, war)) + 
        geom_point() +
        geom_text(aes(label = name_common), check_overlap = TRUE) +
        theme_jtc() 

```

```{r}

process_data <- function(df) {
   
    df %>%
    group_by(player_id) %>%
    filter(min(year_id) >= 1990) %>%
    mutate(
        player_year = year_id - min(year_id) + 1,
    ) %>%  
    ungroup() %>%
    complete(nesting(player_id, position),
             player_year, fill = list(war = -0.5)) %>%
    group_by(player_id) %>%
    arrange(player_year) %>%
    mutate(
        prev_war = lag(war, default = -0.5),
        keep = if_else(min(year_id, na.rm = TRUE) + player_year - 1 > 2019, FALSE, TRUE), 
        lg_id = as.integer(as.factor(lg_id))
    ) %>%
    ungroup() %>%
    arrange(player_id, player_year) %>%
    fill(lg_id) %>%
    filter(keep) %>%
    select(player_id, position, lg_id, player_year, war, prev_war)

}


war_hist <- bind_rows(

    batting %>%
        mutate(position = 1) %>%
        filter(pitcher == "N") %>%
        process_data(),

    pitching %>% 
        mutate(position = 2) %>%
        process_data() 

) 

```

```{r waryear}
library(lme4)

war_hist %>%
    ggplot(aes(player_year, war, group = player_id)) +
        geom_line(alpha = 0.05)

```


## Model specification 

```{r model}
<<<<<<< HEAD

test_players <- sample(unique(war_hist$player_id), 30)

war_hist_processed <- war_hist %>%
    mutate(
        player_index = as.integer(as.factor(player_id)),
        position = as.integer(position),
        player_year = as.integer(player_year)
    ) %>%
    filter(player_id %in% test_players)


war_dat <- list(
    player = as.integer(as.factor(war_hist_processed$player_id)),
    player_year = war_hist_processed$player_year,
    war = war_hist_processed$war
)

war_hist_processed %>%
    ggplot(aes(player_year, war, color = player_id)) +
        geom_point(show.legend = FALSE) 


```
```{r lm}

lm(war ~ poly(player_year, 3), 
   data = war_hist_processed) %>%
    broom::augment(newdata = war_hist_processed) %>%
    ggplot(aes(player_year, .fitted)) +
        geom_line()


```




```{r}

model1 <- ulam(
    alist(
        war ~ dnorm(mu, sigma),
        mu <- a[player] + 
            b * player_year +
            b2 * player_year^2 +
            b3 * player_year^3,
        a[player] ~ dnorm(mu_player, sigma_player),
        mu_player ~ dnorm(2, 1),
        sigma_player ~ dexp(1),
        b ~ dnorm(0, 4),
        b2 ~ dnorm(0, 1),
        b3 ~ dnorm(0, 0.5),
        sigma ~ dexp(1)
    ),
    data = war_dat
)

precis(model1, depth = 2)

preds <- t(link(model1)) %>%
    cbind(war_hist_processed) %>%
    gather(sample, est, 1:500) %>%
    tbl_df()

preds %>%
    ggplot(aes(player_year, war)) +
        geom_point(color = "red") +
        geom_line(aes(
            x = player_year, y = est, 
            group = sample
        ), alpha = 0.01) +
        facet_wrap(~player_id)

```
