---
draft: true
---

Data is a powerful tool. I think it's mostly powerful for two reasons:

1. It can be used to quickly and easily understand lots of lived experiences
2. It is perceived to be objective

The first is a statement about data itself. The second about how people interact with data. I believe many non-profit organizations focus more on the second than the first. 

## The Revolution Will Not Be Data-Driven

Recently I've been reading *The Revolution Will Not Be Funded*. The central theme of the book focuses on the ways in which foundations and government funding of mission-driven organizations can pull them away from their original purpose or intent. Many leaders describe how they were enticed by the opportunity to 'scale' their mission by increasing funding. That funding however comes with ever-growing requirements to demonstrate accountability. Professionalization of organizations means that leaders need to focus more attention on securing money for paying staff.

A trend that 


## Data as emancipatory


